version: '3.7'

services:
  redis:
    image: redis:latest
    command:
      - redis-server
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "6379:6379"
  db:
    image: postgres:15
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgressql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: .
    command: sh -c "make migrate && python -m main"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

volumes:
  pgdata:
