"""empty message

Revision ID: 4d1895bd5abf
Revises: 4e0b356eb149
Create Date: 2023-02-06 23:43:13.218447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1895bd5abf'
down_revision = '4e0b356eb149'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
